require("dotenv").config();
const path=require("path");
const express=require("express");
const cors=require("cors");
const app=express();
const PORT=Number(process.env.PORT)||3000;
app.set("views",path.join(__dirname,"views"));
app.set("view engine","ejs");
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(express.static(path.join(__dirname,"public")));
app.get("/health",(req,res)=>res.json({status:"ok",app:"FAZ NETWORK Server",timestamp:new Date()}));
app.get("/",(req,res)=>res.render("index",{title:"Dashboard",page:"dashboard"}));
app.use((req,res)=>res.status(404).send("Not Found"));
app.listen(PORT,()=>console.log("FAZ NETWORK Server running on port "+PORT));
module.exports=app;
