const express=require("express");
const controller=require("../controllers/packageController");
const router=express.Router();
router.get("/",controller.list);
router.get("/pools",controller.pools);
router.post("/",controller.create);
router.put("/:id",controller.update);
router.delete("/:id",controller.remove);
router.post("/sync",controller.sync);
module.exports=router;
