const express=require("express");
const controller=require("../controllers/paymentController");
const router=express.Router();
router.post("/webhooks/macrodroid-sms",controller.webhook);
router.post("/forward",controller.webhook);
router.post("/verify-trx",controller.verifyTrx);
router.get("/payments/transactions",controller.list);
router.post("/payments/manual-match",controller.manualMatch);
router.get("/payments/summary",controller.summary);
module.exports=router;