const express=require("express");
const controller=require("../controllers/settingsController");
const router=express.Router();
router.get("/general",controller.generalSettings);
router.post("/general",controller.saveGeneralSettings);
router.post("/mikrotik/test",controller.testMikrotik);
router.post("/mikrotik/sync",controller.syncMikrotik);
router.post("/mikrotik",controller.saveMikrotik);
router.post("/mfs-accounts",controller.saveMfsAccounts);
router.get("/hotspot-webhook",controller.hotspotWebhookSettings);
router.post("/hotspot-webhook",controller.saveHotspotWebhookSettings);
router.get("/website",controller.website);
router.post("/website",controller.saveWebsite);
router.get("/hotspot-profiles",controller.hotspotProfiles);
router.get("/hotspot-profile-settings",controller.getHotspotProfileSettings);
router.post("/hotspot-profile-settings",controller.saveHotspotProfileSettings);
router.get("/all",controller.getAllSettings);
router.post("/update",controller.updateSettings);
module.exports=router;
