const crypto=require("crypto");const db=require("../db");const mikrotikService=require("../services/mikrotikService");
function clean(v,max=255){return String(v??"").trim().slice(0,max)}
function errorResponse(res,e){console.error("[Hotspot API]",e);return res.status(e.statusCode||503).json({success:false,error:e.message||"Hotspot operation failed."});}
function randomPin(){return crypto.randomBytes(6).toString("base64url").replace(/[^A-Za-z0-9]/g,"").slice(0,8).toUpperCase();}
async function page(req,res){res.render("hotspot",{title:"Hotspot Vouchers",page:"hotspot"});}
async function profiles(req,res){try{const data=await mikrotikService.getHotspotProfiles();res.json({success:true,profiles:data});}catch(e){return errorResponse(res,e);}}
async function list(req,res){try{const r=await db.query("SELECT * FROM hotspot_vouchers ORDER BY created_at DESC LIMIT 1000");res.json({success:true,vouchers:r.rows});}catch(e){return errorResponse(res,e);}}
async function active(req,res){try{const sessions=await mikrotikService.getActiveHotspotSessions();res.json({success:true,sessions});}catch(e){return errorResponse(res,e);}}
async function generate(req,res){try{const quantity=Math.min(Math.max(Number(req.body.quantity)||0,1),500);const profile=clean(req.body.profile,100),validity=clean(req.body.validity,50),price=Number(req.body.price);if(!profile||!validity||!Number.isFinite(price)||price<0)return res.status(400).json({success:false,error:"Profile, validity, and valid price are required."});const created=[];for(let i=0;i<quantity;i++){let username,password;for(let attempt=0;attempt<10;attempt++){username="FAZ"+randomPin();password=randomPin();const exists=await db.query("SELECT 1 FROM hotspot_vouchers WHERE username=$1",[username]);if(!exists.rows.length)break;}await mikrotikService.createHotspotUser({username,password,profile,comment:"FAZ NETWORK Voucher | Validity: "+validity});await db.query("INSERT INTO hotspot_vouchers(username,password,profile,validity,price,status,comment) VALUES($1,$2,$3,$4,$5,'unused',$6)",[username,password,profile,validity,price,"FAZ NETWORK Voucher"]);created.push({username,password,profile,validity,price});}res.json({success:true,count:created.length,vouchers:created});}catch(e){return errorResponse(res,e);}}
async function remove(req,res){try{const username=clean(req.body.username,100);await mikrotikService.removeHotspotUser(username);await db.query("UPDATE hotspot_vouchers SET status='expired' WHERE username=$1",[username]);res.json({success:true,username});}catch(e){return errorResponse(res,e);}}
module.exports={page,profiles,list,active,generate,remove};
