const db=require("../db");const mikrotikService=require("../services/mikrotikService");
const clean=(v,m=255)=>String(v??"").trim().slice(0,m);
function errorResponse(res,e){console.error("[PACKAGE API]",e);return res.status(503).json({success:false,message:e.message||"Package operation failed."});}
async function pools(req,res){try{res.json({success:true,pools:(await mikrotikService.getIpPools()).filter(x=>!/^default(?:[-_].*)?$/i.test(x.name))});}catch(e){errorResponse(res,e);}}
async function list(req,res){try{const r=await db.query("SELECT * FROM packages ORDER BY plan_name");const p=await mikrotikService.getIpPools(),map=new Map(p.map(x=>[String(x.name).toLowerCase(),x]));res.json({success:true,packages:r.rows.map(x=>({...x,pool_ranges:map.get(String(x.pool_name).toLowerCase())?.ranges||""}))});}catch(e){errorResponse(res,e);}}
async function normalize(b){const v={planName:clean(b.planName,120),poolName:clean(b.poolName,100),profileName:clean(b.profileName||b.planName,120),rateLimit:clean(b.rateLimit,100),price:Number(b.price),durationMonths:Number.parseInt(b.durationMonths||1,10)};if(!v.planName||!v.poolName||!v.profileName||!v.rateLimit||!Number.isFinite(v.price)||v.price<=0||!Number.isInteger(v.durationMonths)||v.durationMonths<1)return{error:"Valid Plan Name, IP Pool, Profile, Rate Limit, Billing Amount and Duration are required."};const p=await mikrotikService.getIpPools(),pool=p.find(x=>String(x.name).toLowerCase()===v.poolName.toLowerCase());if(!pool)return{error:"Selected IP Pool was not found on MikroTik."};v.poolName=pool.name;return{value:v};}
async function syncProfile(v){const p=await mikrotikService.fetchExistingProfiles(),x=p.find(y=>String(y.name).toLowerCase()===v.profileName.toLowerCase());if(x)await mikrotikService.updateProfile(x.id,{name:v.profileName,rateLimit:v.rateLimit,remoteAddress:v.poolName});else await mikrotikService.createProfile({name:v.profileName,rateLimit:v.rateLimit,remoteAddress:v.poolName});}
async function create(req,res){try{const n=await normalize(req.body||{});if(n.error)return res.status(400).json({success:false,message:n.error});await syncProfile(n.value);const r=await db.query("INSERT INTO packages(plan_name,pool_name,profile_name,rate_limit,price,duration_months) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[n.value.planName,n.value.poolName,n.value.profileName,n.value.rateLimit,n.value.price,n.value.durationMonths]);res.status(201).json({success:true,package:r.rows[0]});}catch(e){errorResponse(res,e);}}
async function update(req,res){try{const n=await normalize(req.body||{});if(n.error)return res.status(400).json({success:false,message:n.error});const r=await db.query("UPDATE packages SET plan_name=$1,pool_name=$2,profile_name=$3,rate_limit=$4,price=$5,duration_months=$6,updated_at=NOW() WHERE id=$7 RETURNING *",[n.value.planName,n.value.poolName,n.value.profileName,n.value.rateLimit,n.value.price,n.value.durationMonths,clean(req.params.id,50)]);if(!r.rows.length)return res.status(404).json({success:false,message:"Package not found."});await syncProfile(n.value);res.json({success:true,package:r.rows[0]});}catch(e){errorResponse(res,e);}}
async function remove(req,res){try{const r=await db.query("DELETE FROM packages WHERE id=$1 RETURNING *",[clean(req.params.id,50)]);if(!r.rows.length)return res.status(404).json({success:false,message:"Package not found."});res.json({success:true,package:r.rows[0]});}catch(e){errorResponse(res,e);}}
module.exports={list,pools,create,update,remove};